### PR TITLE
Work around Twisted bug

### LINKED ISSUE #58: Test failure in test_terminal
```
[FAIL]
Traceback (most recent call last):
  File "/home/mithrandi/code/Mantissa/xmantissa/test/test_terminal.py", line 274, in test_write
    self.assertIn('some bytessome more', str(terminal))
  File "/home/mithrandi/deployment/virtualenvs/Mantissa/local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 485, in assertIn
    % (containee, container))
twisted.trial.unittest.FailTest: 'some bytessome more' not in '<xmantissa.test.test_terminal.FakeTerminal instance at 0x7f9a11f42638>'

xmantissa.test.test_terminal.ReturnToMenuTests.test_write
```

This is caused by https://twistedmatrix.com/trac/ticket/8843 which made it into a release, so we probably need to work around it ourselves.

### PR DESCRIPTION
**Pull request by mithrandi**
Fixes #58.

### CODE REVIEW

**Review by glyph — APPROVED** [review]
Looks good to me! Shame about coverage reporting.

**Comment by glyph** [comment]
Re-running the build to see if that will kick codecov.

**Comment by glyph** [comment]
(Since codecov is a required status...)

**Comment by mithrandi** [comment]
Not sure exactly why this happens, but rebuilding the same commit never seems to work; I pushed an empty commit, so let's see what happens with that.

**Comment by glyph** [comment]
Once again travis is done and yet codecov isn't reporting the status.  I'm going to un-require the status until we figure out what's going on here, and land this branch.

**Pull request merged**
