### PR TITLE
PyPy support!

### LINKED ISSUE #42: PyPy support
Mantissa should work on PyPy, and now that conch has switched away from PyCrypto the remaining major headache is gone, so let's officially support PyPy!

### PR DESCRIPTION
**Pull request by mithrandi**
Fixes #42.

I deleted a test entirely for reasons documented in the commit I did it in: fcb3b5f3e1d724539991228d71938b81a9616017

The change to `assertSpacelessEqual` is... really hacky... but I think it should be Good Enough™.

### CODE REVIEW

**Comment by mithrandi** [comment]
Merge #44 first to make the tests pass on this branch.

**Comment by mithrandi** [comment]
Need to get a new PyPy on Travis as well, because of the impending cryptography >= 1.0 constraint.

**Comment by mithrandi** [comment]
That doesn't quite work, I'm just going to switch to using tox but I'll do that in a separate branch to keep the diff size down.

**Comment by hawkowl** [comment]
@mithrandi merged forward, there's some hilarious(tm) pypy test failures still :(

**Comment by mithrandi** [comment]
@hawkowl The remaining failures are resolved by #44, but since that's a big chunk of diff that's almost entirely unrelated to this branch, I decided to just put a (different) workaround here as well.

**Comment by mithrandi** [comment]
Okay, there's also a giant tox mess now because everything is terrible.

**Comment by glyph** [comment]
Is this just codecov screwing up or is this a real issue?

**Comment by mithrandi** [comment]
@glyph: It's a result of turning on branch coverage in this branch; I don't think any actual coverage was _lost_ in this branch.

**Comment by glyph** [comment]
@mithrandi should we push an empty commit to master?

**Comment by mithrandi** [comment]
@glyph: It would have to be a commit that turns branch coverage on in master, not an empty commit.

**Comment by glyph** [comment]
@mithrandi Even better: small branches.

**Comment by mithrandi** [comment]
@glyph: Okay, I guess I'll try that and see what breaks (heh).

**Comment by mithrandi** [comment]
@glyph Okay, there's still some diff from _version.py vanishing from coverage due to the directory changing shenanigans, but now the coverage diff looks sensible I think.

**Comment by glyph** [comment]
OK. Let's do it.

**Pull request merged**
