### PR TITLE
Generate default certificate with Cryptography instead of certcreate

### LINKED ISSUE #43: X.509 cert generation should use Cryptography, not certcreate
certcreate kinda sucks (and has a bug that affects this code on pypy), we should just use `cryptography.x509`.

### PR DESCRIPTION
**Pull request by mithrandi**
Fixes #43.
#45 introduced a workaround into the tests that this branch needs to remove, don't land until #45 has landed and I've updated this branch.

### CODE REVIEW

**Comment by glyph** [comment]
This looks like a massive increase in the amount of code, and I don't fully understand the consequences (and it no longer merges) so I'm going to close, but please reopen after commenting on #43 :)

**Comment by mithrandi** [comment]
@glyph I can't make this and #45 mergeable simultaneously, and #45 was the last PR anyone tried to review so I made that one mergeable instead of this one.

**Comment by glyph** [comment]
All right, let's get #45 landed, then please feel free to reopen this now that I understand your motivations (expressed on #43 ) a bit better.

**Comment by mithrandi** [comment]
Um. The codecov commit status is slightly confused, but I think everything else looks good? (Querying the weird commit status in the codecov gitter room, so let's not merge just yet)

**Comment by glyph** [comment]
absolute numbers on codecov look OK, although the comparison looks weird. Let me know as soon as you get a support resolution.

**Comment by mithrandi** [comment]
@glyph: Okay, codecov problems sorted out, sort of.

This is the correct link for the coverage changes: https://codecov.io/gh/twisted/mantissa/compare/757552d83e23f52c13080089f8b4c7fcdd052ca3...9f3ad4c66c61886ec750a34a10fba19d622eefef/changes

I don't really understand how those lines had partial coverage before, I think this is some coverage.py weirdness?

**Comment by glyph** [comment]
I am re-running the build on master to see if the "no build to compare against" issue goes away.

**Comment by mithrandi** [comment]
@glyph: The "no build to compare against" issue is because the commit status points to the wrong URL; the correct one is the one in my comment. Codecov are still working on investigating / fixing the commit status URL, I believe.

**Comment by glyph** [comment]
All right. Let's just land this then and fiddle with codecov later.

**Pull request merged**
